language: "python"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master

python:
  - "2.7"
  #- "pypy"

env:
  - MODE=inplace
  - MODE=sdist
  - MODE=wheel

install:
  # Upgrade pip/setuptools
  - pip install -U pip setuptools
  # Tools for checking coverage and uploading to coveralls
  - pip install coveralls coverage
  - |
    python setup.py --version
    if [ "${MODE}" == "inplace" ]; then
        pip install --editable .
    elif [ "${MODE}" == "sdist" ]; then
        python setup.py sdist
        pip install dist/Mantissa-"$(python setup.py --version)".tar.gz
    elif [ "${MODE}" == "wheel" ]; then
        pip install wheel
        python setup.py bdist_wheel
        pip install dist/Mantissa-"$(python setup.py --version)"-py2-none-any.whl
    fi

script:
  - cd /tmp && coverage run --branch --source=xmantissa $(type -p trial) xmantissa
  - cd /tmp && coverage report -m

after_success:
  - cd /tmp && coveralls

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
