language: "python"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master

env:
  - MODE=inplace
  - MODE=sdist
  - MODE=wheel

matrix:
  include:
    # PyPy isn't supported just yet
    #- python: "pypy"
    - python: "2.7"

install:
  # Tools for checking coverage and uploading to coveralls
  - pip install coveralls coverage
  - |
    if [ "${MODE}" == "inplace" ]; then
        pip install --editable .
    elif [ "${MODE}" == "sdist" ]; then
        python setup.py sdist
        pip install dist/Mantissa-"$(python setup.py --version)".tar.gz
    elif [ "${MODE}" == "wheel" ]; then
        pip install wheel
        pip wheel
        pip install dist/Mantissa-*.whl
    fi

script:
  - coverage run --branch --source=xmantissa $(type -p trial) xmantissa
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
