language: "python"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master

env:
  - TOXENV=py27-twlatest
  - TOXENV=py27-twtrunk
  - TOXENV=py27-tw14
  - TOXENV=pypy-twlatest
  - TOXENV=pypy-twtrunk
  - TOXENV=pypy-tw14
  # Test inplace on one variant
  - TOXENV=py27-twlatest DEVELOP=--develop

matrix:
  allow_failures:
    - env: TOXENV=py27-twtrunk
    - env: TOXENV=pypy-twtrunk

install:
  # Install a newer PyPy version
  - |
    if [ "${TOXENV::5}" == "pypy-" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy-5.0.1
      pyenv global pypy-5.0.1
    fi
  - pip install -U pip setuptools wheel
  - pip install tox codecov

script:
  - tox ${DEVELOP}

after_success:
  - codecov

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
